name: maap-tropess-deploy
channels:
- conda-forge
dependencies:
- python
- requests
- boto3
- pyyaml
- dateparser
- pip
- pip:
  - cwltool
  - dotenv
  - maap-py
  - mdps-app-generator>=1.1.0
  # For the Python package, that uses the binary installed into Conda above
  - --extra-index-url https://artifactory.jpl.nasa.gov/artifactory/api/pypi/pypi-release-local/simple
  - tropess-product-spec>=2.5.2